### PR TITLE
Feature 2

### PR DESCRIPTION
**Pull request by lidaquan888**
Hi guys, Can I merge these to branch master?

### CODE REVIEW

**Comment by lidaquan888** [comment]
@lidaquan999 
have a look at the feature_2.txt

**Comment by lidaquan999** [comment]
@lidaquan888 
Are you sure the feature_2 is done?
I mean that there is no feature detail in feature_2.txt, and review this file please.

**Comment by lidaquan888** [comment]
@lidaquan999 
Have a look at it again

**Comment by lidaquan999** [comment]
@lidaquan888 
OK, I think you can do your merge.

**Comment by lidaquan999** [comment]
hello, guys!

**Comment by lidaquan888** [comment]
hi, man!

**Pull request merged**
